version: 2.1

orbs:
  python: circleci/python@0.3.2
jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test

  lint-and-coverage:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            python3 tests.py
      - run:
          name: Linter
          command: |
            flake8 src/
            flake8 test/
      - run:
          name: Coverage
          command: |
            coverage run
            coverage report

      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows:
  main:
    jobs:
         - build-and-test
         - lint-and-coverage
         
