version: 2.1

orbs:
  python: circleci/python@0.3.2
jobs:
  test-on-k8s:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Kubelibrary container image
          command: |
            docker build -t kubelibrary -f testcases/Dockerfile .
      - k3d/k3d-helpers
      - k3d/k3d-up:
          cluster-name: testk3d-2
          #k3s-bin-version: v4.4.2

workflows:
  main:
    jobs:
      - test-on-k8s:
          filters:
            tags:
              only: /.*/
         
